spring:
  liquibase:
    change-log: classpath:/liquibase/db.changelog-master.yml
    enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/whiskey
    username: root
    password: 'mihairu'
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  rabbitmq:
    user: guest
    password: guest
    host: localhost
    port: 5672

server:
  port: 1225

#api:
#  product: http://localhost:5555